/**
 * tokens.json -> tokens.css (for the web app) + tokens.export.json (for the
 * video and social pipelines).
 *
 *   node packages/design-tokens/src/build.mjs
 *
 * The CSS is emitted inside Tailwind v4's `@theme` block, so `--color-ink`
 * both exists as a custom property and generates `bg-ink` / `text-ink`
 * utilities. One name per value, everywhere - two names for one colour is how
 * a design system drifts.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const PKG = path.resolve(HERE, '..');

const raw = JSON.parse(await readFile(path.join(PKG, 'tokens.json'), 'utf8'));

/** @type {Record<string, string>} flat css-var-name -> value */
const flat = {};
/** @type {Record<string, Record<string, {value: string, note: string, cssVar: string}>>} */
const structured = {};

for (const [groupName, group] of Object.entries(raw.groups)) {
  structured[groupName] = {};
  for (const [key, token] of Object.entries(group.values)) {
    const cssVar = group.cssPrefix ? `--${group.cssPrefix}-${key}` : `--${key}`;
    flat[cssVar] = token.value;
    structured[groupName][key] = { value: token.value, note: token.note, cssVar };
  }
}

// --- tokens.css -------------------------------------------------------------

const lines = [
  '/* GENERATED by packages/design-tokens/src/build.mjs - do not edit by hand. */',
  '/* Edit packages/design-tokens/tokens.json and run `npm run tokens:build`.  */',
  '',
  '@theme {',
];

for (const [groupName, group] of Object.entries(raw.groups)) {
  lines.push(`  /* ${groupName} */`);
  for (const [key, token] of Object.entries(group.values)) {
    const cssVar = group.cssPrefix ? `--${group.cssPrefix}-${key}` : `--${key}`;
    lines.push(`  ${cssVar}: ${token.value};`);
  }
  lines.push('');
}

lines.push('}', '');

await writeFile(path.join(PKG, 'tokens.css'), lines.join('\n'), 'utf8');

// --- tokens.export.json -----------------------------------------------------

const exported = {
  $generated: 'packages/design-tokens/src/build.mjs - do not edit by hand',
  meta: raw.meta,
  tokens: structured,
  css: flat,
};

await writeFile(
  path.join(PKG, 'tokens.export.json'),
  `${JSON.stringify(exported, null, 2)}\n`,
  'utf8',
);

const count = Object.keys(flat).length;
console.log(`tokens: ${count} values -> tokens.css + tokens.export.json`);
